version: '3'
services:
  zookeeper-ch:
    image: zookeeper:3.5
    container_name: zookeeper-ch
    hostname: zookeeper-ch
    privileged: true
    networks:
      - ugc

  clickhouse-node1:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    privileged: true
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./cluster_clickhouse/node1:/etc/clickhouse-server
    networks:
      - ugc
    depends_on:
      - zookeeper-ch

  clickhouse-node2:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse-node2
    hostname: clickhouse-node2
    privileged: true
    volumes:
      - ./cluster_clickhouse/node2:/etc/clickhouse-server
    networks:
      - ugc
    depends_on:
      - zookeeper-ch

networks:
  ugc:

volumes:
  cluster_clickhouse:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './cluster_clickhouse'
