version: '3'
services:
  etl:
    build: ./etl/
    env_file:
      - .env
    networks:
      - ugc
    depends_on:
      users_analyze_api:
        condition: service_healthy
      clickhouse-node1:
        condition: service_healthy

  users_analyze_api:
    build: ./users_analyze_api/src/
    env_file:
      - .env
    networks:
      - ugc
    expose:
      - "8000"
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:8000' ]
      interval: 5s
      timeout: 3s
      retries: 5

  zookeeper-ch:
    image: zookeeper:3.5
    container_name: zookeeper-ch
    hostname: zookeeper-ch
    privileged: true
    networks:
      - ugc

  clickhouse-node1:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    privileged: true
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./cluster_clickhouse/node1:/etc/clickhouse-server
    networks:
      - ugc
    depends_on:
      - zookeeper-ch
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:8123' ]
      interval: 5s
      timeout: 3s
      retries: 5

  clickhouse-node2:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse-node2
    hostname: clickhouse-node2
    privileged: true
    volumes:
      - ./cluster_clickhouse/node2:/etc/clickhouse-server
    networks:
      - ugc
    depends_on:
      - zookeeper-ch

networks:
  ugc:

volumes:
  cluster_clickhouse:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './cluster_clickhouse'
