version: '3.4'
services:
  clickhouse:
    image: yandex/clickhouse-server:20.3
    container_name: clickhouse
    hostname: clickhouse
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"